version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the Node.js app"
      - npm run build
  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
