version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build steps"
  post_build:
    commands:
      - echo "Build complete, starting application"

artifacts:
  files:
    - '**/*'
